# Generated by Django 5.0.7 on 2024-07-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_course_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_credits',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_usn',
        ),
    ]
