# Generated by Django 5.0.7 on 2024-07-23 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
